### ISSUE TITLE
An easier way to integrate Cangjie codes into Anthy

### ISSUE THREAD

**Issue by Des-Nerger** [fcitx/fcitx5-anthy#10]
Not long time ago I migrated to `fcitx5-anthy` from `ibus-anthy`.
There, I could integrate the Cangjie codes into Anthy by converting [libcangjie's table.txt](https://gitlab.freedesktop.org/cangjie/libcangjie/-/tree/master/data) using my [little script](https://gist.github.com/Des-Nerger/5713142c97ec97e7cf109ce51770a6d1), into a format like this:
```
# ~/.anthy/private_words_default
...
あjっm #T35*500 暄
あjつ #T35*500 暁
あjぬ #T35*500 晼
あjぷ #T35*500 晓
あjむ #T35*500 晥
あk #T35*500 旲
あkcf #T35*500 暸
...
```
and then reload them through the kasumi GUI tool. I used such an Anthy+Cangjie5 input method for years and it was very convenient for me as a Japanese learner. This approach continued to work somewhat fine even after the migration to `fcitx5-anthy`. However, yesterday I started noticing issues caused by differences between how `ibus-anthy` converts latin to kana, and how `fcitx5-anthy` does it. For example, `ce` is converted to `cえ` by ibus-anthy, whereas converted to `せ` by fcitx5-anthy; so I can't input `暴` anymore.
I thought the most robust way for me to fix this is to write quick-and-dirty C++ code with some dummy `fcitx::AddonManager` and `fcitx::KeyEvent` implementations to extract the needed "partial kana" output. But it feels complex [I never wrote for `fcitx` before; and rarely write in C++ these days (usually Rust)]. Do you have an idea of a better way to solve this? :thinking:

**Comment by wengxt** [comment]
The ce rule was introduced with this commit, 

https://github.com/fcitx/fcitx5-anthy/commit/fd6d8a488cd1812756f7ad5f23c2fa5c4f8902d8

So, I assume you’re using a romaji table for this?

You may create a new sty file for romaji table and use it to override the default romaji table.

Check the sty file that comes with the package so you have an idea about the format.

Make a copy of the any file, and write the old rule under [RomajiTable/FundamentalTable] (by checking the rule in the prior the commit above).

Then, save the file to ~/.local/share/fcitx5/anthy/[somefilename].sty

Then go to config, and set Romaji Table option to custom, and fill the file name in the “Custom Romaji Table” to make it use the romaji rule in your sty file.

**Comment by Des-Nerger** [comment]
After some trying and failing with other approaches I came up with [a more universal solution of simulating keypresses to produce what I wanted](https://github.com/Des-Nerger/retyping_cangjie5codes_for_anthy). (The only drawback of which is that it takes more than hour to finish.)
...
Long story short, here's ready-made `~/.anthy/private_words_default` I produced using/for fcitx5-anthy v5.1.3: [private_words_default.zip](https://github.com/fcitx/fcitx5-anthy/files/14533307/private_words_default.zip)

But there's one more caveat to be worth noting here (an except from my repo's `README.md`):
> * The performance of recent versions of the `kasumi` GUI tool, when resaving a big dictionary, is quite awful, even impractical to do on HDD (and I don't recommend anyone to wear out their SSDs, either). So move the anthy directory onto a ramdisk first and symlink it: `$ mv ~/.anthy /dev/shm && ln -sv {/dev/shm/,~/}.anthy`.
> * Run `$ kasumi` itself, press `Save`, and when it finishes, press `Close`.
> * Get the anthy directory back in its place: `$ gio trash ~/.anthy && mv /dev/shm/.anthy ~`.

**Comment by wengxt** [comment]
Err, it seems that you're trying to simulate keyboard with xdo tool and redirect that into cangjie.

This is not really necessary.
You can directly talk to fcitx instead, with either
1. cretae a dbus client and send key to fcitx5.
or
2. Use fcitx as a library, like how fcitx run e2e test.
Some example for doing this, 
https://github.com/fcitx/fcitx5-chinese-addons/blob/master/test/testpinyin.cpp 
This should be much much faster than you simulate key event.
