### ISSUE TITLE
kao kanji missing 

### ISSUE THREAD

**Issue by tramtrist** [fcitx/fcitx5-anthy#3]
When I type kao and hit space I expect to see anthy to show me many faces (moji) 
This works with fcitx4 but not fcitx5

**Comment by wengxt** [comment]
I tried fcitx4 and didn't see the same thing. I wonder if this requires some special dictionary.

**Comment by wengxt** [comment]
Just to make sure we're on the same page:
Fcitx 4
![图片](https://user-images.githubusercontent.com/259684/149986577-5a1dc4c9-8434-458b-9798-fec2f07c0f59.png)

Fcitx 5
![图片](https://user-images.githubusercontent.com/259684/149986717-1e317f05-3c07-45a9-bac4-6c422f744a48.png)

Basically same thing on my side.

**Comment by tramtrist** [comment]
I was wrong about this!!! I will close this ticket 🙇

**Comment by tramtrist** [comment]
This was a mistake on my part
