### ISSUE TITLE
fcitx5-anthy 输入弹出框在dwl(wayland)下不显示

### ISSUE THREAD

**Issue by guyuming76** [fcitx/fcitx5-anthy#6]
我装完 fcitx5-anthy 后(https://github.com/fcitx/fcitx5/discussions/660) 。在 dwm (xorg) 下虚拟终端窗口里， ctrl+space 切换到anthy, 键盘输入字母，会出现一个“横长条”的弹出窗口，里面显示些假名，这时如果按两下空格，还会出现一个“竖长条” ,可以上下键选择,并回车选词。

可是，在dwl(wayland) 里，anthy输入状态下，键盘输入并不会显示，也就是说那个“横长条”弹出框不会显示，直到我按两下空格键，“竖长条”会显示（如下图），我可以上下键移动回车选词。
![anthy1](https://user-images.githubusercontent.com/12045548/203674578-9973a144-9ba1-4b7a-9747-9970e2601d1e.png)

我看了 dwl 和 fcitx5 的日志，如下图，似乎是 ctrl+space 键切换到anthy输入状态后fcitx5 log 里立刻会有 zwp_input_popup_surface_v2@19.destroy. 
下图左边显示的dwl 日志里相应地也是 IM_new_popup_surface 后立刻就有im_popup_destroy. 

![anthy2](https://user-images.githubusercontent.com/12045548/203674671-4a84b134-87b6-40e6-8690-9367246cee08.png)

我若是切换到中文拼音输入法，一切都是正常的。

**Comment by rocka** [comment]
https://github.com/djpohly/dwl/pull/235

dwl 不支持 text-input 和 input-method 协议

**Comment by guyuming76** [comment]
是的，dwl 主分支不支持中文日文输入，这个235 PR 支持

基于这个PR235, 我做了些小修改： https://gitee.com/guyuming76/dwl/tree/fixDnD 。这里我提的问题，在PR235和我的修改上都会出现。

**Comment by guyuming76** [comment]
input_popup_surface destroy 的调用栈：
![anthy3](https://user-images.githubusercontent.com/12045548/203685918-a3acc7c2-8b7b-41c0-9b4c-95ef5f5bb717.png)

oldvisible 是 true 的，visible()是 false, 这个直接导致了popup surface destroy
![anthy4](https://user-images.githubusercontent.com/12045548/203685936-8fad22e4-1e72-4064-9666-95cb568b0684.png)

**Comment by guyuming76** [comment]
inputwindow.cpp:288 里得到的 candidateList 总是空的，导致 visible_ 为 false

![anthy5](https://user-images.githubusercontent.com/12045548/203689799-2e976db0-122a-4573-b0df-cd58de3dc2e1.png)

**Comment by wengxt** [comment]
你调试的方法大概不对。调试输入法和焦点之间关系很重要 
https://fcitx-im.org/wiki/Debug_fcitx5#GDB_or_other_debuggers

首先anthy 的用法就是弹出窗口是按空格才会出现的
你说的横条应该是 preedit ，你应该关注 preedit ，有没有把 preedit 从输入法转发给 text input。

根据描述肯定不是 fcitx 的 问题，close。

**Comment by guyuming76** [comment]
在 https://github.com/djpohly/dwl/pull/235 改动的代码里，是可以找到 wlr_text_input_v3_send_preedit_string 调用的， 位于 handle_im_commit 方法里。

我根本不知道“正确”的交互流程是如何，所以无从判断是 dwl PR的问题，还是fcitx问题，或者anthy问题。

**Comment by wengxt** [comment]
我只能告诉你别的compositor，weston，kwin和sway都能正常用

**Comment by guyuming76** [comment]
> 我只能告诉你别的compositor，weston，kwin和sway都能正常用

我想在weston里对比下，就装了weston, 但拼音输入没配好，我建了各新问题：https://github.com/fcitx/fcitx5/discussions/665
